site_name: aichampionslearn.github.io
site_description: Website of AIChampionsHub for Collaborative learning
site_url: https://aichampionslearn.github.io

site_author: AIChampionsLearn
repo_url: https://aichampionslearn.github.com/
repo_name: AIChampionsLearn/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  custom_dir: overrides
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: False
      include: ["*.ipynb"]  # Default: ["*.py", "*.ipynb"]
      # ignore: ["some-irrelevant-files/*.ipynb"]
      execute: True
      allow_errors: false
      execute_ignore: "my-secret-files/*.ipynb"
      kernel_name: python3
      theme: dark
      include_source: True
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - awesome-pages:
  # - awesome-nav
  - blog:
      blog_dir: .
      blog_toc: true
      post_url_format: "{slug}"
  - tags:
      tags_file: tags.md
  - privacy:
      links: 
      links_attr_map:
        target: _blank
      links_noopener: true
      enabled: true
      assets_exclude:
        - cdn.jsdelivr.net/npm/mathjax@3/*
        - giscus.app/*
  - git-committers:
      enabled: true
      repository: aichampionslearn/
      branch: main
      token: !ENV GH_TOKEN
  - glightbox:
      touchNavigation: false
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true
  - minify:
      minify_html: true
  - rss:
      match_path: "posts/.*"
      pretty_print: false
      rss_feed_enabled: true
      date_from_meta:
        as_creation: date.created
        as_update: date.updated


extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: simple/youtube
      link: https://youtube.com/@stbalaji
    - icon: fontawesome/brands/github-alt
      link: https://github.com/AIChampionsLearn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/stbalaji
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/stbalaji/

extra_css:
  - stylesheets/extra.css

hooks:
  - hooks/socialmedia.py

# For Code extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

copyright: |
  &copy; 2024 <a href="https://github.com/AIChampionsLearn"  target="_blank" rel="noopener">AIChampionsLearn</a>
